WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
text = @{ ASCII_ALPHANUMERIC+ | "!" | "?" | "~" | "^" | "=" | "'" | "\"" }
elementName = @{ ASCII_ALPHANUMERIC+ }
element = {
    "<" ~ elementName ~ ">"
    ~ (element | text)*
    ~ "</" ~ elementName ~ ">"
}

attrName = @{ ASCII_ALPHANUMERIC+ }
attrValue = { text }
elementAttr = {
    attrName ~ "=" ~ attrValue
}

html = _{
    SOI
    ~ element
    ~ EOI
}