use std::str;
use crate::ast::{Element};

grammar;

pub Html: Element = {
    Tag
}

pub Tag: Element = {
    Text => Element::new(String::from(<>)),
    "<" <t:ElementName> ">" Tag "</" <s:ElementName> ">" => {
        if t != s {
            return Element::new(String::from("error"));
        }
        Element::new(t)
    },
}

ElementName: String = {
    r"[a-z]+" => format!("{}", <>)
}

Text: String = {
    r"[a-z]+" => format!("{}", <>)
}
